//
// Created by rahul on 24/06/2017.
//

#ifndef LAMBDACALCULUSINTERPRETER_TOKENTYPE_H
#define LAMBDACALCULUSINTERPRETER_TOKENTYPE_H


enum class TokenType {
    LAMBDA, DOT, LPAREN, RPAREN, SENTINAL, LCID
};


#endif //LAMBDACALCULUSINTERPRETER_TOKENTYPE_H
