//
// Created by rahul on 25/06/2017.
//

#ifndef LAMBDACALCULUSINTERPRETER_ASTENTITYTYPE_H
#define LAMBDACALCULUSINTERPRETER_ASTENTITYTYPE_H


enum class AstEntityType {
    ABSTRACTION,
    APPLICATION,
    IDENTIFIER,
    BASE,
    EPSILON
};


#endif //LAMBDACALCULUSINTERPRETER_ASTENTITYTYPE_H
